# Generated by Django 3.2.25 on 2025-08-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddress',
            name='memployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_addresses', to='payroll_manager.memployee'),
        ),
        migrations.AlterField(
            model_name='memployee',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_for_employee', to='payroll_manager.maddress'),
        ),
        migrations.AlterUniqueTogether(
            name='mpay',
            unique_together={('fin_year', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='mpaygrade',
            unique_together={('employee', 'grade')},
        ),
    ]
